<div class="account-container">
  <div class="about">
    <h1>Sobre o projeto</h1>
    <p>A nossa equipe é composta por: <strong>Pedro</strong> e <strong>Cauã</strong>, obrigado pela atenção, fizemos nosso projeto com muito esforço (e muito ódio pra ser síncero).</p>
    <p>O tema é <strong>ordem de serviço</strong>, então criamos esse sitema onde você cadastra seu equipamento e cria uma ordem de serviço referente a ele, nossos técnicos então poderão vizualizar, aceitar ou recusar e entrar em contato com você</p>
  </div> 
  <div class="img-container">
    <?php importImg('aboutImg.svg') ?>
  </div>
</div>