<div class="top">
  <a class="logo-container" href="/">
    <?php importImg('logo.svg') ?>
    <?php importImg('logo-mobile.svg') ?>
  </a>
</div>
<div class="account-container register">
  <form action="/user/action/check/register" method="POST">
    <h1>Crie sua conta</h1>
    <label class="input-block">
      <span class="label">Nome</span>
      <input class="custom" name="name" type="text">
      <span></span>
    </label>
    <label class="input-block">
      <span class="label">Email</span>
      <input class="custom" name="email" type="email">
      <span></span>
    </label>
    <div class="row passwords">
      <label class="input-block">
        <span class="label">Senha</span>
        <input class="custom" name="password" type="password">
        <span></span>
      </label>
      <label class="input-block">
        <span class="label">Confirmar senha</span>
        <input class="custom" name="confirm_password" type="password">
        <span></span>
      </label>
    </div>
    <button class="custom" type="submit">Registrar</button>
    <a class="custom" href="/login">Já possui uma conta?</a>
  </form>
  <div class="img-container">
    <?php importImg('loginImg.svg') ?>
  </div>
</div>