  

  <script src="/frontend/js/global.js" type="module"></script>
  <script src="/frontend/js/events/submits.js" type="module"></script>
  <script src="/frontend/js/events/keyups.js" type="module"></script>
  <script src="/frontend/js/events/clicks.js" type="module"></script>
  <script src="/frontend/js/events/change.js" type="module"></script>
  <script src="/frontend/js/routes.js" type="module"></script>
</body>
</html>
