<!DOCTYPE html>
<html>

<head>
  <link href="https://fonts.googleapis.com/css2?family=Poppins&amp;display=swap" rel="stylesheet">
  <link type="text/css" rel="stylesheet" href="/frontend/css/tailwind.css" media="screen,projection" />
  <link rel="stylesheet" href="/frontend/css/styles.css">
  <link rel="icon" href="/frontend/assets/logo.svg">
  <title>Assistência técnica (ordem de serviço)</title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />
</head>

<body class="bg-gray-100">