<?php if (!isset($_GET['reduced'])) { ?>
  <!DOCTYPE html>
  <html>

  <head>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Archivo:wght@400;600&family=Poppins&display=swap" rel="stylesheet">
    <link rel="icon" href="/frontend/assets/logo.svg">
    <link rel="stylesheet" href="/frontend/css/global.css">
    <title>ServiTech PC • <?= URL ?></title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
  </head>

  <body>
    <?php } ?>
    <div id="root" class="<?= isset($_SESSION['id']) ? 'logged' : '' ?>">
    
    <?php if(isset($_SESSION['id'])) require(__DIR__.'/../components/Dashboard.phtml') ?>